#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Cipher\Console\CipherCommand;
use Symfony\Component\Console\Application;

(new Application('Cipher CLI Tool'))
    ->add($command = new CipherCommand)
    ->getApplication()
    ->setDefaultCommand($command->getName(), true)
    ->run();
